language: python
python:
- '3.5'
cache: pip
script:
- ./bin/test
- coveralls
deploy:
- provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: janrain-mailchimp
  env: mailchimp-beanstalk-nyyimby-prod-va
  bucket_name: elasticbeanstalk-us-east-1-882324420608
  bucket_path: travis-janrain-mailchimp
  skip_cleanup: true
  on:
    branch: master
